name: CI

on:
  push:
    branches:
      - main
      - 'releases/**'
  pull_request:
    branches:
      - main
      - 'releases/**'

jobs:
  tests_e2e:
    name: Run end-to-end tests
    runs-on: ubuntu-latest
    steps:
      # 해당 저장소의 코드를 가져옵니다.
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 패키지를 설치합니다.
      - name: Install dependencies
        run: yarn install

      # e2e(playwright) 테스트 툴을 설치합니다.
      - name: Install playwright browsers
        run: npx playwright install --with-deps

      # e2e 테스트를 수행합니다.
      - name: Run e2e tests
        run: yarn e2e:ci
